version: "3"
x-common-gss:
  &default-common-gss
  environment:
    &default-common-env-gss
    POSTGRES_USER: test
    POSTGRES_PASSWORD: test
services:
  gss:
    build: .
    environment:
      << : *default-common-env-gss
      POSTGRES_URL: "postgres:5432/test"
      MOBILE_PASSWORD: testPwd
#      KEYSTORE: keystore_file.db
#      KEYSTORE_PASSWORD: keystore_password
    deploy:
      resources:
        limits:
          memory: 1G
    ports:
      - 8080:8080
#    volumes:
#      - /path/workspace:/workspace
  postgres:
    image: postgis/postgis:13-3.1
    environment:
      << : *default-common-env-gss
      POSTGRES_PORT: 5432
      POSTGRES_DB: test
#    ports:
#      - 5432:5432
#    volumes:
#      - /path/data:/var/lib/postgresql/data
