name: flutter_server
description: Geopaparazzi Survey Server.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # MIT
  #font_awesome_flutter: 8.5.0
  #community_material_icon: 3.5.95
  material_design_icons_flutter: 3.2.4495

  # Apache 2.0
  charts_flutter: 0.8.1

  # MIT
  provider: 3.1.0

  # MIT
#  google_atlas: 0.2.1

  # BSD
#  webview_flutter: 0.3.14+1

  # apache
  latlong: 0.6.1

  # MIT
  fab_circular_menu: 0.1.1

  # Apache 2.0
  flushbar: 1.9.0

  # MIT
  flutter_tags: ^0.4.3

  # BSD
  flutter_map:
    git:
      url: https://github.com/johnpryan/flutter_map.git

  # BSD
  flutter_map_marker_cluster:
    git:
      url: https://github.com/moovida/flutter_map_marker_cluster.git

  transparent_image: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/gss_logo.png
   - assets/smash_logo.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
