version: "3"

x-common-healthcheck:
  &common-healthcheck
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 30s

x-common-postgres-env:
  &common-postgres-env
  POSTGRES_USER: ${GSS_POSTGRES_USER}
  POSTGRES_PASSWORD: ${GSS_POSTGRES_PASSWORD}
  POSTGRES_PORT: ${GSS_POSTGRES_PORT}
  POSTGRES_DB: ${GSS_POSTGRES_DB}

x-common-postgres:
  &common-postgres
  image: postgis/postgis:15-3.3
  hostname: postgres
  ports:
    - ${GSS_POSTGRES_PORT}:5432
  environment:
    << : *common-postgres-env
  healthcheck:
    << : *common-healthcheck
    test: ["CMD", "pg_isready", "-U", "${GSS_POSTGRES_USER}"]

x-common-django:
  &common-django
  hostname: django
  build:
    context: ../server_backend_django
    dockerfile: ../docker/Dockerfile.django
  image: gss-docker-django
  environment:
    &common-django-env
    << : *common-postgres-env
    POSTGRES_HOST: postgres
  healthcheck:
    << : *common-healthcheck
    test: ["CMD", "curl", "-sI", "http://localhost:8000/admin"]

x-common-nginx:
  &common-nginx
  hostname: nginx
  build:
    context: ..
    dockerfile: docker/Dockerfile.https
  image: gss-docker-nginx
  environment:
    DJANGO_URL: http://django:8000
  ports:
    - 80:8000
    - 443:443

services:
  nginx:
    << : *common-nginx
    depends_on:
      django:
        condition: service_healthy
    volumes:
      - ${GSS_VOLUME}/server/static:/var/www/static:ro
      - ${GSS_VOLUME}/server/media:/var/www/media:ro
  django:
    << : *common-django
    environment:
      << : *common-django-env
      SECRET_KEY: ${GSS_SECRETKEY}
      DEBUG: "false"
      ALLOWED_HOSTS: "localhost ${GSS_ALLOWED_HOSTS}" 
      CORS_ALLOWED_ORIGINS: "${GSS_ALLOWED_ORIGINS}"
      CSRF_TRUSTED_ORIGINS: "${GSS_ALLOWED_ORIGINS}"
      WEB_CONCURRENCY: 4 # gunicorn workers
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ${GSS_VOLUME}/server/static:/app/static
      - ${GSS_VOLUME}/server/media:/app/media
  postgres:
    << : *common-postgres
    volumes:
     - ${GSS_VOLUME}/server/data:/var/lib/postgresql/data

